### ISSUE TITLE
Very high noise rates?

### ISSUE THREAD

**Issue by Helveg** [Igor10798/Internship#1]
https://github.com/Igor10798/Internship/blob/82fc91cd8b7b1e8a8986b16f4321e473fa4928a6/scripts/first_network.py#L194

40 & 60 kHz seems like an awfully large frequency? Usually in neural networks you don't go about 100-300Hz, especially never above 1000Hz as that is the maximum bandwidth of neurons.

**Comment by igorcantele** [comment]
Fixed! I used those frequencies because in the docs I found 80kHz and 15kHz rates, and in some simulation ex I found high frequencies too.
With so low rates I had some troubles in making the inhibitory pop to fire, thus I adjusted weights and `I_e` in `deterministic.py`, and in `aleatory_conn.py` I introduced a new input
