### ISSUE TITLE
Watch out with version docs

### ISSUE THREAD

**Issue by Helveg** [Igor10798/Internship#2]
You're using NEST 2.18, don't be confused by the 2.20 docs:

> I looked in the docs the functions I did not know and I used the chance to look at the functions related to the simulation in the docs (https://nest-simulator.readthedocs.io/en/nest-2.20.1/ref_material/pynest_apis.html?highlight=resetkernel#module-nest.lib.hl_api_simulation), implementing them in the first_project.py file in order to run multiple simulations.
>
>Comments
>I could not find in the docs the property "synaptic_elements" for the "iaf_psc_alpha" object, so I could not understand how it works... Maybe I can add new properties to neurons (?)

**Comment by igorcantele** [comment]
You're right!
I must have forgotten to change the version when looking for `ResetKernel`, I'll be more careful.

Edit.
Since in the example I used the version of nest wasn't reported, I tired to run the script and it worked. But it uses functions (e.g. `SetStructuralPlasticityStatus` that are not present in 2.18 doc.
