### ISSUE TITLE
`create_network` should strictly `create` only

### ISSUE THREAD

**Issue by Helveg** [Igor10798/Internship#9]
https://github.com/Igor10798/Internship/blob/9c8a19fcba446cb2e43bf0a8b77ce410f15c4c85/first_network/script.py#L44-L64

All of this code does not belong in `create_network`, it should only construct the network and return the IDs of the important nodes (cells, recorders, ...) The simulation and analysis belongs in the main scope

**Comment by Igor10798** [comment]
I tried to create a `label_network` function with spikeDet as argument (returned by `create_network`) but it couldn't find it.

**Comment by Helveg** [comment]
You can close my issues commit by commit, and then mention "closes #9" (or the relevant issue number) so that GitHub closes the issue automatically and leaves a link for me to follow so that I can see exactly which changes you made to fix the issue.

**Comment by igorcantele** [comment]
Oh thank you, sorry!
I'll do it next time.

I don't know if you saw the other e-mail, but in case I wanted to inform
you that I "completed" the task about neural network, but I'm probably
missing some error because of the plots.
Here I wrote a sort of preliminary analysis:
https://github.com/Igor10798/Internship#16062021-scriptpy-httpsgithubcomigor10798internshipblobmasterfirst_networkscriptpy
.


Il giorno lun 21 giu 2021 alle ore 19:34 Robin De Schepper <
***@***.***> ha scritto:
